name: Autodeploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # fetch full history if needed

    # Build your site here if you need to
    # For example, if you use Jekyll, Hugo, or other static site generator.
    # Example:
    # - name: Build site
    #   run: |
    #     npm install
    #     npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .   # change this to your build output folder if you build (e.g., ./public, ./dist, etc.)
        force_orphan: true  # recreate gh-pages from scratch (similar to what you did before)
